### PR TITLE
Misc tweaks

### PR DESCRIPTION
**Pull request by tsibley**
Several commits making small changes.  Please give a look over, thanks!  In particular, I'd appreciate a sanity check that the change to `camelcase_to_snakecase` doesn't totally break your full dataset processing.  (I don't yet have a full ViPR dataset that works locally, as discussed in Slack.)

### CODE REVIEW

**Comment by trvrb** [comment]
@tsibley: You don't think it's better form to peg to particular versions in `requirements.txt` that are known to work? This had been my philosophy. Also, I was trying to keep versions consistent between sacra and augur (https://github.com/nextstrain/augur/blob/master/requirements.txt). So if someone globally installs there won't be conflicting version requirements between the packages.

**Comment by tsibley** [comment]
There are definitely advantages to pinning/pegging/freezing exact versions, and I'm happy to rework my commit to stick to that route if you'd like.  It's also useful to try to coordinate deps between projects, but IME it's less necessary to do so when you're not pinning exact versions because conflicts don't tend to arise when using non-exact version specs.

I guess I tend to see a distinction between "what this project requires" (requirements.txt or Gemfile or package.json) and "the exact versions for deploy" (i.e. conda's environment.yaml or Gemfile.lock or package-lock.json, or Docker more generally).

If we don't want to change augur's requirements.txt right now, then I should definitely rework my commit so that conflicts don't arise between the two approaches (pinning vs. not).

**Comment by trvrb** [comment]
Let's distinguish between `requirements.txt` and lock file. Keep the commit and also do the same for augur. We should start making lock files as part of the repos as well. We are currently smart about this for auspice (which has `package.json` and `package-lock.json`).

**Comment by tsibley** [comment]
Ok, sounds good.  I'm on the fence about using something simple and hopefully obvious like `pip freeze > requirements-locked.txt` versus introducing more tooling and using [Pipenv](https://docs.pipenv.org/). Do you or @barneypotter24 or @huddlej have any thoughts here?

**Comment by trvrb** [comment]
I like the simple `requirements-locked.txt` idea. For augur, we should also be thinking about how to express the dependencies on `raxml`, `mafft`, etc... needing to be able to be run from the command line.

**Comment by tsibley** [comment]
I'll go with `requirements-locked.txt`.

There is no general way to express deps on external binaries in the path without committing to a general-purpose package manager like conda or apt or containers.  The goal of making it easy to bootstrap up a nextstrain setup can standardize on one or more of those, but that's a different task.

**Comment by trvrb** [comment]
>There is no general way to express deps on external binaries in the path without committing to a general-purpose package manager like conda or apt or containers. The goal of making it easy to bootstrap up a nextstrain setup can standardize on one or more of those, but that's a different task.

Great. Completely agree.

**Comment by tsibley** [comment]
repushed

**Pull request merged**
